# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/

# different stages in the pipeline
stages:
    - test
    - build
    - publish

variables:
    # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
    DOCKER_REGISTRY: 324466407431.dkr.ecr.us-east-2.amazonaws.com
    APP_NAME: app-dash-corona


test_job:
    stage: test
    script:
        - python --version
        - pip install -r requirements.txt
        - pip install pytest --quiet
        - pytest -v
    image: python:3.7-slim

build_job:
    stage: build
    services:
        - docker:19.03.12-dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build --pull -t $CONTAINER_TEST_IMAGE .
        - docker push $CONTAINER_TEST_IMAGE
        - docker run --env APP_MODE_ENV=TEST -p 80:80 $CONTAINER_TEST_IMAGE 
    image: docker:19.03.12

publish_job:
    stage: publish
    image: 
        name: amazon/aws-cli
        entrypoint: [""]
    services:
        - docker:dind
    before_script:
        - amazon-linux-extras install docker
        - aws --version
        - docker --version
    script:
        - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $DOCKER_REGISTRY
        - docker tag $CONTAINER_TEST_IMAGE:latest $DOCKER_REGISTRY/$APP_NAME:latest
        - docker push $DOCKER_REGISTRY/$APP_NAME:latest
        - aws ecs update-service --cluster $CI_AWS_ECS_CLUSTER --service $CI_AWS_ECS_SERVICE --force-new-deployment

